checkpoints
adevinta/vulcan-scan-engine pull request #49
Opened 2023-02-06 15:45 UTC by jesusfcr

- fix go warnings
- Update scan state every N checks created
- Improve logs
- Update ChecksCreated at the end to close the scan

2023-02-21 09:17 UTC, manelmontilla requested changes

2023-02-21 09:19 UTC, jesusfcr commented on cmd/vulcan-scan-engine/commands/root.go
> +	informer := apiclient.NewCachedChecktypeInformer(apiClient, 10*time.Second)
this is already addressed in the last commit

2023-02-21 09:36 UTC, jesusfcr commented on pkg/scans/checksrunner.go
> +				// Always executes for the first time to validating the scanTerminated.
thans

2023-02-21 10:09 UTC, jesusfcr commented on pkg/apiclient/apiclient.go
> +	s.cache.Set(assettypeKey, &assettypes, cache.DefaultExpiration)
right, thanks

2023-02-21 10:11 UTC, jesusfcr commented on pkg/apiclient/apiclient.go
> +func NewCachedChecktypeInformer(api *client.Client, expiration time.Duration) CachedApiClient {
right!

2023-02-21 10:19 UTC, jesusfcr commented on go.mod
> +	github.com/patrickmn/go-cache v2.1.0+incompatible
Replaced by my own implementation

2023-02-21 11:26 UTC, jesusfcr commented on pkg/apiclient/apiclient.go
> +type CachedApiClient struct {
done

2023-02-21 11:27 UTC, jesusfcr commented on pkg/api/service/scans.go
> +	GetAssettypes() (*client.AssettypeCollection, error)
To avoid having to create objects. Storing just the reference.

2023-02-21 11:28 UTC, jesusfcr commented on pkg/apiclient/apiclient.go
> +		cache:  cache.New(expiration, cache.DefaultExpiration),
changed implementation

2023-02-21 12:08 UTC, jesusfcr commented on pkg/scans/checksrunner_test.go
>  				}
Added the checkpoint value (before was 0). Not sure if you mean to also test the behaviour of stopping the process and restarting again.

2023-02-21 12:09 UTC, jesusfcr commented on pkg/apiclient/apiclient.go
> +
done

2023-02-23 16:30 UTC, manelmontilla approved these changes
LGTM

2023-02-24 08:24 UTC, merged